"""Authoring source. Rows are handwritten; build.py expands auditable JSON."""
# 16 reusable access states, not permanent classes. Every choice names tomorrow's access.
CONTEXTS = {
'c_oath':('王庭','王令持有者','王国'), 'c_ledger':('王庭','账簿调查者','王国'), 'c_revolt':('王庭','抗命者','民众'), 'c_guard':('王庭','护送者','同伴'),
'h_oath':('教会','守誓者','教会'), 'h_ledger':('教会','禁书读者','教会'), 'h_revolt':('教会','异端证人','魔族'), 'h_guard':('教会','收容者','民众'),
'w_oath':('龙境','契约者','龙族'), 'w_ledger':('龙境','遗迹测绘者','龙族'), 'w_revolt':('龙境','夺火者','龙族'), 'w_guard':('龙境','护卵者','同伴'),
'v_oath':('边境','民兵代表','民众'), 'v_ledger':('边境','渡口组织者','民众'), 'v_revolt':('边境','离群者','同伴'), 'v_guard':('边境','守家人','民众')}
# choice = visible | next access | dominant dimension | irreversible deed | immediate cost/result
D1 = [
('带着故乡的粮单，响应王都召集。','c','Courage','answered_summons','你得到入城凭证；村里的青壮少了一个。'),
('去圣辉教会，核对预言中被抹去的人名。','h','Faith','sought_prophecy','你得到抄经人的席位；教会登记了你的家乡。'),
('进入精灵旧林，寻找黎明留下的剑痕。','w','Freedom','entered_forest','你避开王国征召；熟悉的道路也到此为止。'),
('拒绝召集，留下修复故乡的渡桥。','v','Mercy','refused_summons','老人今晚仍有人照看；召集令上你的名字被划去。')]
D2 = {
'c':('粮单与冠冕','阿尔维恩的城门只向四类人开启：能作战的、能付钱的、能证明有用的，以及有人担保的。骑士玛伦替你作保，却把你的粮单压在一摞阵亡通知之下。摄政莱娅答应派粮，但她需要一个在广场上接受勇者封号的人。账房的墨还没有干，名单里已有三座被放弃的村庄。城外的队伍等不到下一次议事。',[
'签下征召誓书，换取故乡的粮车。|c_oath|Faith|obeyed_kingdom|粮车出发；你须接受王庭征用。',
'留下核对军粮账，暂缓出征。|c_ledger|Reason|audited_grain|找到虚报数字；玛伦独自赶往前线。',
'当众读出被放弃的村名，逼王庭答复。|c_revolt|Freedom|challenged_crown|城外难民得到听证；粮车被扣作证物。',
'拿担保书护送难民，放弃受封。|c_guard|Sacrifice|escorted_refugees|难民获准过门；你的勇者席位由别人接替。']),
'h':('钟楼下的删文','钟声响了六次，第七声迟迟没有来。修女伊芙说那口钟只在封印稳定时鸣响；执事却坚持只是钟轴生锈。你带来的预言抄本少了一页，装订线里夹着七百年前的血。院外有人要烧死一名带角的信使，院内有人在为人类伤兵缝合伤口。他们唱的是同一首圣歌，教皇瑟文正在两扇门之间等你的回答。',[
'接下夜祷誓约，以服从换取进入钟楼。|h_oath|Faith|obeyed_church|你获准接近封印仪表；不能公开所见。',
'替修女抄完病历，交换被删的书页。|h_ledger|Reason|read_forbidden|找到历代勇者同样的病症；错过公开听证。',
'把魔族信使带到广场，要求公开审理。|h_revolt|Freedom|saved_demon_child|信使妮娅暂免火刑；你被记为争议证人。',
'关上收容所大门，同时收留两族伤兵。|h_guard|Mercy|opened_shelter|伤兵免受围攻；医院粮票被暂时冻结。']),
'w':('没有守卫的剑','精灵旧林的路牌全部朝向来处。地图师缇尔说，林子不是在驱逐你，而是在给你最后一次离开的机会。断裂的祭坛上没有宝石，只有一柄被布条包住的剑。它没有审问你的善恶，只让你看见自己死去的样子。更深处传来龙卵敲壳的声音，山下猎人已经点起熔炉。你来寻找力量，力量却先提出了要保护什么的问题。',[
'以性命作证，拔出圣剑黎明。|w_oath|Courage|took_holy_sword|黎明接受你的信念；封印开始把痛觉传给你。',
'放下剑柄，测绘祭坛下的古代管道。|w_ledger|Reason|refused_holy_sword|你看见能量流向；试炼资格不再保留。',
'夺走猎人的熔炉芯，用它打开禁林。|w_revolt|Ambition|stole_furnace|你取得不受教会控制的火；猎人冬季生计被毁。',
'先转移龙卵，把寻剑的时间让出去。|w_guard|Mercy|protected_egg|幼龙离开猎场；另一名求剑者进入祭坛。']),
'v':('桥只够过一辆车','河水把桥墩磨成了骨头的颜色。父亲留下的工具仍在门边，村长托马没有问你为什么没去当勇者，只问明早能过几辆车。驻军要拆桥阻止魔族斥候，船工要留桥转移病人。妮娅送来上游决堤的消息，没有人愿意相信一个魔族孩子。你留下以后，故乡没有变得简单：至少有三种死亡正在沿着不同的路接近。',[
'接受临时民兵印，带人守住桥头。|v_oath|Courage|formed_militia|村里有了警戒队；孩子们开始叫你长官。',
'征用自己的屋梁，加固渡船并登记乘客。|v_ledger|Reason|built_ferry|病人可以夜渡；你的家再也挡不住雨。',
'带家人从山路撤离，把工具留给村长。|v_revolt|Freedom|fled_village|家人离开交战区；其他村民仍在等待。',
'留下照看走不了的人，让年轻人先走。|v_guard|Sacrifice|stayed_with_weak|无人被独自遗弃；你失去白天撤离的机会。'])}
# Each day has 16 authored menus. Four routes out of every menu are distinct.
D3 = {
'c_oath':('印玺的背面','你的王令能让粮仓开门，也能让士兵征走最后一匹马。玛伦请你在军需单上签字，单子背面却粘着一张平民的求救信。',[
'签征马令，亲自跟随粮队承担责问。|c_oath|Courage|requisitioned_horses|粮队能赶上防线；村民失去春耕牲口。',
'把王令交给修女，请她核查征用名单。|h_ledger|Reason|shared_writ|军需接受外部审计；王庭不再独信你。',
'烧掉征用单，让每户自行决定是否出马。|c_revolt|Freedom|burned_order|农户保住选择权；军粮晚到一夜。',
'用自己的军饷雇船，不让士兵进村。|v_ledger|Mercy|paid_transport|粮食沿河前行；你没有钱购买护身药。']),
'c_ledger':('账外的冬粮','消失的军粮并不全在贵族地窖里。账房奥伦用假账养着一座未被王国承认的麻风村；同一条运输线也在出售军情。',[
'封存全部账目，要求公开听证。|c_revolt|Freedom|published_accounts|贪腐无法隐去；麻风村失去秘密供给。',
'保留救济支出，只追查军情买家。|h_ledger|Reason|separated_accounts|追查方向变窄；你必须替部分假账担责。',
'接管运输线，用情报收入养活病人。|c_oath|Ambition|lied_for_power|救济继续；走私者开始称你东家。',
'送出自己的行粮，再押奥伦去教会作证。|h_guard|Sacrifice|protected_witness|证人和病人都有退路；你将空腹赶路。']),
'c_revolt':('广场没有屋顶','你的发言让民众聚集，也让城门成为弓弩的靶场。莱娅承诺会谈，但要求你交出最先敲钟的工匠。工匠说自己愿意坐牢，却不肯认罪。',[
'陪工匠入狱，用自己换一场正式听证。|h_oath|Sacrifice|shared_sentence|弩手撤离；你接受教会监视。',
'抢占钟楼，迫使摄政交出粮仓钥匙。|c_revolt|Ambition|seized_bell|粮仓立刻开门；守卫在冲突中受伤。',
'带人退出广场，把听证搬到难民营。|c_guard|Mercy|deescalated_square|孩子离开射程；你的声势迅速减弱。',
'接受密谈，用不公开账目换三日粮食。|c_ledger|Reason|lied_for_good|饥民吃上饭；工匠不再相信你的透明承诺。']),
'c_guard':('车轮下面','难民车队抓到一名魔族少年，背包里装着绘有防线的地图。妮娅认出那是她哥哥的笔迹：地图同时标着一处将被洪水淹没的营地。',[
'护送少年去教会，让双方共同验图。|h_revolt|Mercy|saved_demon_child|少年保住性命；车队行程暴露给教会。',
'按军法处死持图者，立即转移防线。|c_oath|Reason|killed_demon_child|地图不再外传；一名未受审的少年死去。',
'跟少年绕往上游，亲自验证洪水消息。|w_ledger|Courage|verified_warning|能确认危险；车队暂失你的保护。',
'让玛伦押人，自己带老弱走另一条路。|v_guard|Sacrifice|split_convoy|老人继续前进；你放弃替少年决定命运。']),
'h_oath':('誓词里的空位','你获准进入钟楼。仪表记录的不是魔力，而是某个人七百年的心跳。瑟文请你把那个人仍然活着的事实写成神迹。',[
'宣读神迹，争取教会统一撤离命令。|h_oath|Faith|lied_for_good|教区接受调度；谎言由你亲口延续。',
'只公布心跳数据，暂不解释它属于谁。|h_ledger|Reason|published_measurement|学者可以复核；民间开始出现相反传言。',
'拒绝宣读，把原卷交给魔族学者。|h_revolt|Freedom|rejected_church|另一方获得证据；教会撤销你的通行证。',
'请求守在仪表旁，分担一次封印脉冲。|w_oath|Sacrifice|shared_burden|陌生人的痛苦减轻；你的手留下黑纹。']),
'h_ledger':('同一张病历','七位不同时代的勇者留下相同的伤口图。伊芙说，她救过一名魔族士兵，伤口里也有同样的黑砂。有人在外面索要这些病历作为异端罪证。',[
'把病历交给王庭工匠，要求盲审。|c_ledger|Reason|cross_checked_records|获得独立测量；病人的秘密离开医院。',
'将病历藏入自己的衣衬，独自查旧林。|w_ledger|Freedom|hid_records|证据不被没收；伊芙可能受你牵连。',
'签名承认抄本归你，保护伊芙留下。|h_guard|Sacrifice|shielded_eve|医院保住医师；你承担异端指控。',
'以病历要挟执事，换取封印室钥匙。|h_oath|Ambition|blackmailed_clergy|你得到门钥；教会记住这笔债。']),
'h_revolt':('证人的舌头','妮娅的证词能证明魔族平民正在撤离，却也会暴露一条秘密山道。魔族将领瓦尔请求你删去山道位置；他不愿说这条路还会运输什么。',[
'保留完整证词，允许双方观察员到场。|c_ledger|Reason|open_testimony|证言更可信；山道居民必须连夜搬迁。',
'删去坐标，只公开平民撤离的事实。|h_guard|Mercy|lied_for_good|居民位置保密；证词留下可被攻击的缺口。',
'让妮娅自己决定，并陪她承担后果。|v_revolt|Freedom|respected_witness|她保有发言权；你的阵营支持变得不确定。',
'拒绝军方条件，护送妮娅回魔族营地。|w_guard|Courage|escorted_nia|孩子离开审讯；公开审理无法完成。']),
'h_guard':('一床两伤','最后一瓶止血药放在伊芙掌心。左床的人类军官掌握撤离口令，右床的魔族工兵知道封印排水渠。两人都清醒，也都听见了你们的讨论。',[
'先救军官，换取医院的通行口令。|c_guard|Reason|saved_officer|撤离手续可办；工兵留下永久伤残。',
'先救工兵，请他带伤员走地下渠道。|w_ledger|Mercy|saved_engineer|排水渠可以启用；军官失去一条腿。',
'稀释药物同时施救，接受两人的风险。|h_guard|Faith|shared_medicine|两人都愿配合；下一日医疗资源减少。',
'献出自己的血，把整瓶药留作术后急救。|v_guard|Sacrifice|gave_blood|两人暂时稳定；你无法参加今晚的追捕。']),
'w_oath':('剑没有宣判','黎明在你掌中发热，却没有阻止猎人殴打盗粮者。缇尔提醒你，剑回应的是肯付出的意志，而不是善恶。猎人也愿意为饿着的女儿去死。',[
'立下供粮契约，请古龙担保双方停手。|w_oath|Faith|bound_dragon_pact|暴力暂止；你必须偿还猎人的粮债。',
'交出自己的口粮，让盗粮者去王庭作证。|c_guard|Mercy|fed_prisoner|囚犯免遭私刑；你和缇尔将挨饿。',
'拔剑砍断猎人的武器，禁止私刑。|w_revolt|Courage|stopped_lynching|盗粮者活下来；猎人失去防身工具。',
'把剑暂寄祭坛，去查为何供粮中断。|c_ledger|Reason|questioned_sword|你获得账目线索；暂时不能靠剑震慑。']),
'w_ledger':('地下的河','古代管道从教堂、王宫和龙巢同时流向山腹。缇尔发现系统仍在工作，维修铭文却被凿掉。开启检修门需要停止一处供能。',[
'停王宫暖炉，进入主检修道。|c_revolt|Freedom|cut_palace_heat|工匠得到入口；宫中病人也将受冻。',
'借龙卵的余温供能，请龙族观察维修。|w_guard|Mercy|borrowed_egg_heat|检修不伤居民；孵化被推迟。',
'请求教会熄灭圣灯，记录一次完整波形。|h_ledger|Reason|measured_abyss|获得可靠波形；全城看见圣灯熄灭。',
'用自己的生命火种启动旧机器。|w_oath|Sacrifice|life_powered_machine|不用切断任何街区；你开始咳血。']),
'w_revolt':('被夺走的冬天','熔炉芯能破开龙鳞，也能让山镇度过寒冬。猎人头领追到断桥，没有要求你归还一切，只要你保证他的女儿不会冻死。',[
'归还一半炉芯，凭残余力量继续前进。|w_guard|Mercy|returned_heat|山镇得到供暖；你失去强攻龙巢的把握。',
'把炉芯献给王庭，换一队合法护卫。|c_oath|Ambition|traded_furnace|护卫归你调遣；山镇要向王国买煤。',
'邀请猎人入伙，让他共同决定炉芯用途。|v_oath|Freedom|shared_power|猎人愿意带路；你不能独占力量。',
'吞入炉芯灰烬，以自身替代燃料。|w_revolt|Corruption|ate_ash|力量留在你体内；你开始听见陌生人的愿望。']),
'w_guard':('巢外的契约','古龙阿瑟兰没有为你护卵道谢。它问，如果龙的孩子需要烧毁一片村庄才能活，你是否仍会保护它。缇尔说，龙的誓言通常从这种问题开始。',[
'要求龙族先保护人类村庄，再谈孵化。|v_oath|Reason|negotiated_dragon|互助条件明确；古龙认为你缺乏敬意。',
'以自己的体温守卵，给村庄争取时间。|w_guard|Sacrifice|warmed_egg|无需点燃村庄；你将错过一天休息。',
'拒绝预设牺牲，寻找另一处地热口。|w_ledger|Freedom|sought_third_heat|发现旧时代井道；追捕者也会找到巢穴。',
'答应缔约，但保留公开违约的权利。|w_oath|Faith|conditional_oath|古龙承认你是谈判者；关系从一条不信任开始。']),
'v_oath':('长官的第一道命令','民兵在谷口发现两支队伍：王国溃兵带着伤者，魔族侦察兵带着水源图。桥只能容一支先过，另一支必须面对涨水。',[
'先接伤者，要求王国交出撤退地图。|c_guard|Mercy|rescued_wounded|重伤者上岸；魔族侦察队被困。',
'先接侦察兵，交换下游全部水源坐标。|h_revolt|Reason|traded_water_map|几个村庄获救线索；溃兵怀疑你的立场。',
'带民兵分拆桥板，同时搭两条索道。|v_ledger|Courage|built_two_crossings|两边都能开始过河；民兵承担落水风险。',
'要求两军缴械混编，再一起过桥。|v_oath|Ambition|disarmed_armies|桥头不再受军队控制；你接下看守俘虏的责任。']),
'v_ledger':('名单最后一行','渡船的重量上限比乘客名单少三个人。托马把自己的名字划掉，另两名老人却不愿替任何人作榜样。妮娅带来一条穿过禁林的小径。',[
'按伤情安排上船，自己带其余人走禁林。|w_guard|Mercy|led_forest_evacuation|重伤者先行；步行队面临迷路。',
'留下粮袋腾位置，渡河后向王庭求粮。|c_ledger|Reason|dumped_supplies|所有乘客能上船；明天必须找到粮食。',
'征用驻军快艇，以村庄债券作抵押。|c_oath|Ambition|issued_village_debt|运力足够；故乡背上未来税债。',
'留在岸上修第二条船，请托马领队。|v_guard|Sacrifice|stayed_to_build|撤离可以继续；你暂时和家人分开。']),
'v_revolt':('山路朝着身后','你已经能看见安全领的烽火。身后传来桥钟，它本该在所有人过河后敲响，现在却提前了三个时辰。家人紧握你的袖口，没有要求你回头。',[
'送家人到哨站后折返桥头。|v_oath|Courage|returned_after_flight|家人安全；你必须在黑夜独自赶路。',
'把口粮托给巡队，继续带家人前行。|v_revolt|Freedom|kept_fleeing|家人不再涉险；你只能间接帮助故乡。',
'向教会报告钟声，请求开放避难所。|h_guard|Faith|requested_sanctuary|救援获得坐标；教会也取得你们的名册。',
'去最近的龙井引水，为村庄争一夜。|w_ledger|Reason|diverted_flood|洪水推迟；安全领的农田可能遭淹。']),
'v_guard':('留下的人','老人把炉边的位置让给一个魔族伤兵。伤兵是工兵萨德，承认他曾炸毁王国的桥，也承认自己的部队不会回来接他。外面的巡逻队要你交人。',[
'把萨德藏在地窖，请他帮忙修桥。|h_revolt|Mercy|sheltered_sad|桥有机会修好；你的家成为军事目标。',
'要求巡队签下不处决保证，再移交伤兵。|c_guard|Reason|secured_trial|村庄免于搜查；你依赖一份脆弱的保证。',
'以民兵代表身份拒绝搜屋。|v_oath|Courage|defended_home|老人保有安宁；你公开对抗驻军。',
'随伤兵一起离开，把追兵引向旧林。|w_guard|Sacrifice|drew_pursuit|村庄暂时脱险；你失去守在家旁的机会。'])}
D4 = {
'c_oath':('王令以下的真相','莱娅交出一份只有摄政才能看的继任诏书。每一位勇者名字后面，都留着一个尚未填写的死亡日期。她的父亲拒绝过选拔，代价是北岸三万人死于黑潮。',[
'接受候选容器的训练，要求撤离名单公开。|h_oath|Faith|accepted_training|你争到公开撤离；王庭开始把你视为耗材。',
'扣下诏书，召集工匠寻找替代方案。|c_ledger|Reason|learned_truth|研究获得法律掩护；传统继任被延误。',
'向广场承认真相，也承认你曾服从。|c_revolt|Freedom|confessed_lie|谣言有了可核实的证人；秩序短暂崩解。',
'先用王令迁走北岸居民，再追究王庭。|c_guard|Mercy|evacuated_north|更多人逃出危险区；知情者获得销毁证据的时间。']),
'c_ledger':('并不存在的胜利','账簿中七百年前的庆功宴之后，是向魔王城持续七百年的药材供给。奥伦把运单与现任封印心跳对齐：被运送的不是毒药，而是止痛药。',[
'保留药路，向王庭索要容器维修预算。|c_oath|Reason|maintained_medicine|旧容器得到药；你接手维持谎言的账。',
'带一箱止痛药去见所谓魔王。|h_revolt|Mercy|carried_medicine|会谈有了诚意；人类护卫拒绝与你同行。',
'复制运单交给各地医师，再毁掉原件坐标。|h_guard|Freedom|distributed_evidence|真相不会被单方封存；下一批送药需要改路。',
'沿药路追踪深渊入口，亲自测量失控速度。|w_ledger|Courage|discovered_abyss|得到现场数据；你暴露在黑潮辐射下。']),
'c_revolt':('胜利的口号','你公开的证据被印成传单，最末一行却被改成“杀尽教士”。工匠维克承认印坊已失去控制。广场另一端，几个教士正在为踩踏伤者包扎。',[
'挡住追打教士的人，承认运动已经伤人。|h_guard|Mercy|protected_clergy|受伤教士活下来；激进派指责你背叛。',
'接管印坊，所有传单先经你批准。|c_oath|Ambition|controlled_press|煽动暂时停止；言论重新需要许可。',
'让教皇公开回应原件，接受双向质询。|h_ledger|Reason|held_public_hearing|双方证词被记录；会谈消耗撤离时间。',
'带着愿同行的人离城，建立无王令的避难营。|v_revolt|Freedom|founded_free_camp|一部分人脱离冲突；城里温和派失去组织者。']),
'c_guard':('被救者的名字','伤员玛伦认出封印画像中的人：不是被杀死的魔王，而是史书里的第一代勇者艾德里安。她问你是否还要把这批伤员送去参加所谓讨伐。',[
'取消讨伐护送，把伤员送往渡口。|v_ledger|Mercy|cancelled_hunt|伤者不再赴死；封印室缺少守卫。',
'告诉玛伦真相，请她自愿带队护送药品。|h_revolt|Faith|trusted_maren|骑士获得选择权；部分人当场离队。',
'暂不告诉全队，以救援名义继续向山腹走。|c_ledger|Reason|lied_for_good|队伍保持完整；信任将来要由你偿还。',
'独自去替伤员守住封印外门。|w_oath|Sacrifice|held_outer_gate|伤员得到休息；你承担第一轮深渊冲击。']),
'h_oath':('神谕的呼吸','瑟文带你见到钟楼下的传声管。所谓女神答复，有些来自祭司，有些来自旧机器，还有些连教皇也无法解释。他愿以自己的命证明维持封印不是骗局。',[
'继续守誓，但要求誓词写明容器的同意权。|h_oath|Faith|reformed_oath|信徒保留共同语言；强制选拔受到约束。',
'拒绝替不明声音作证，将传声管公开封存。|h_revolt|Freedom|faith_broken|你保住诚实；失去对祈祷仪式的控制。',
'让学者、龙族与祭司共同辨认声音。|w_ledger|Reason|studied_oracle|来源可以交叉核验；各方争抢解释权。',
'接替教皇承受一次回流，确认他是否说谎。|w_oath|Sacrifice|tested_burden|你证实回流真实；体内黑纹扩散。']),
'h_ledger':('七百年的同一个人','删去的最后一页写着第一代勇者的亲笔请求：“若有人还能承受，就不要再称他为怪物。”伊芙发现王国与魔族都在删改这句话，各自只保留对自己有利的半句。',[
'公布完整原件，连同各方删改痕迹。|c_revolt|Freedom|learned_truth|任何阵营都难独占解释；脆弱停火面临考验。',
'将原件交给艾德里安，请他确认自己的意愿。|h_revolt|Mercy|met_previous_hero|旧勇者重新成为能回答的人；你必须进入魔王城。',
'先研究他的病历，寻找容器以外的承压方式。|w_ledger|Reason|researched_lattice|找到分散承压的假说；它还没有安全验证。',
'封存原件，换取教会为伤员开仓。|h_guard|Sacrifice|bargained_archive|医院得粮；真相暂时仍受权力保管。']),
'h_revolt':('魔王没有宝座','艾德里安坐在一把维修椅上，背后是穿过骨骼的银管。他知道历代勇者的名字，因为每一个都曾来这里问过是否还有别的办法。瓦尔在门外要求他给战争背书。',[
'陪他拒绝瓦尔的战争誓书。|h_revolt|Mercy|reconciled_hero|旧勇者不再孤立；魔族军方撤走守卫。',
'先替他接上止痛管，再询问深渊结构。|w_ledger|Reason|discovered_abyss|你得到清醒的证词；输药消耗医院库存。',
'接受他的一次记忆灌注，亲历首次封印。|w_oath|Faith|received_memory|篡改的历史有了体验证据；记忆可能侵蚀自我。',
'把瓦尔叫进来，要求他也为战争承担容器风险。|c_revolt|Courage|challenged_warlord|将领不能只让别人付出；谈判随时可能破裂。']),
'h_guard':('医院里的魔王画像','伤者听见真相后没有立刻互相原谅。人类军官仍记得萨德炸断的桥，萨德也记得教会焚毁的村。伊芙把两人的床隔开，说止痛不能代替审判。',[
'建立共同病历，救治与追责分别进行。|h_ledger|Reason|separated_care_trial|医院保住中立；两边军方都嫌处理太慢。',
'请双方先互相指认失踪平民，寻找活人。|v_ledger|Mercy|listed_missing|复仇暂让位于救援；受害者得不到即时惩罚。',
'允许伤者拒绝和解，保证他们都能离院。|v_revolt|Freedom|refused_forced_peace|个人边界得到尊重；共同队伍可能瓦解。',
'替医院签下赔偿债，让双方先释放人质。|c_guard|Sacrifice|assumed_reparation|人质获释；你背下无法一人偿清的债。']),
'w_oath':('黎明承认的怪物','古龙说黎明曾在艾德里安手中，也曾回应准备屠城的继任者。它认得愿付生命的信念，无法判断信念是否值得。剑柄的热度只是你自己的决心。',[
'给自己的用剑权加上同伴否决条款。|c_guard|Mercy|limited_sword|同伴敢于劝阻；战场决策变慢。',
'要求古龙教你承压，而不学习杀戮。|w_oath|Faith|learned_containment|容器训练开始；你主动接近不可逆风险。',
'将剑的性质告诉公众，拒绝天选者身份。|c_revolt|Freedom|rejected_chosen|人们能质疑持剑者；联盟失去简单旗帜。',
'把剑接入测量阵列，验证它能否分散黑潮。|w_ledger|Reason|tested_sword_lattice|得到关键实验；武器暂时离手。']),
'w_ledger':('龙骨是管道','缇尔发现所谓古龙墓地是深渊泄压系统。龙族守护墓地，也垄断了维修知识；七百年前它们同意单一容器方案，是为了不让自己的族群长期承压。',[
'以测量证据要求龙族共同承担压力。|w_guard|Reason|exposed_dragon_role|龙族必须回应旧债；谈判失去礼仪保护。',
'保留墓地秘密，交换完整的维修图。|w_oath|Faith|kept_dragon_secret|图纸到手；你也成了隐瞒者。',
'把骨管接到无人荒原，做小规模试排。|v_ledger|Courage|tested_empty_channel|新方案取得数据；荒原生态受到损伤。',
'拆取一段龙骨制造自己的承压器。|w_revolt|Ambition|took_dragon_bone|你获得独立装备；祖先遗骨受到冒犯。']),
'w_revolt':('力量的饥饿','炉芯与黑潮发生共鸣。瓦尔愿用一份屠龙图换你替他打开人类边防；阿瑟兰则愿烧毁一个魔族营地，换你交还炉芯。两份交易都把平民写成了空地。',[
'拒绝两份交易，公布营地中的平民名单。|h_revolt|Freedom|rejected_war_bargain|双方借口失效；你失去军力支持。',
'只取古龙脱落的鳞，放弃完整龙晶。|w_guard|Mercy|spared_dragon|古龙愿继续谈；你的承压器功率受限。',
'伏击古龙夺晶，将其余力量交给撤离队。|c_guard|Ambition|killed_dragon|撤离队得到强力屏障；龙族不会遗忘这次杀戮。',
'用炉芯吸收黑潮试样，亲身查清代价。|w_revolt|Corruption|absorbed_abyss|你取得难以复制的数据；欲望开始带有别人的声音。']),
'w_guard':('幼龙也会燃烧','幼龙第一次喷火，烧伤了替它准备食物的村民。阿瑟兰愿赔偿，却要求任何人不得记录伤者姓名，以免龙族受辱。幼龙蜷在你的衣角里。',[
'要求公开道歉，把幼龙留在中立医院。|h_guard|Mercy|dragon_accountability|伤者得到承认；龙族的骄傲受损。',
'替村民接受赔偿，隐去龙族责任。|c_ledger|Reason|lied_for_good|伤者立即获得药钱；事实被你的签名掩盖。',
'教幼龙自己道歉，拒绝替它决定一生。|v_guard|Freedom|raised_dragon|它学会停下火焰；风险仍需社区承担。',
'让幼龙返回族群，自己留作赔偿人质。|w_oath|Sacrifice|became_hostage|双方暂时不再争夺它；你失去自由通行。']),
'v_oath':('没有被选中的人','托马找到旧村志：第一代勇者出发时，也只是负责修渠的年轻人。召集令之外，还有许多人维持了封印。民兵却开始要求你像王一样决定谁能留下。',[
'成立轮值议事会，交出永久指挥权。|v_ledger|Freedom|shared_command|民兵获得共同程序；紧急决定不再只由你作出。',
'接受战时指挥，写下七日后的交权日期。|c_oath|Courage|temporary_command|调度集中；交权承诺将受权力考验。',
'训练两族伤兵守护撤离队。|h_guard|Mercy|mixed_guard|更多家庭获得护卫；队内仇恨尚未消除。',
'亲自守在洪水缺口，让议事会继续开会。|v_guard|Sacrifice|held_floodgate|人们有时间商量；你承受整夜水压。']),
'v_ledger':('地图上的空白村','王都提供的撤离图没有你的故乡，也没有魔族河岸聚落。空白处恰好是泄压系统的旧出口。工匠维克说，修复它能救王都，却可能淹没这些房屋。',[
'先登记所有空白村，再动工修渠。|v_ledger|Reason|mapped_all_villages|风险能被计算；抢修时间变少。',
'向两岸居民说明代价，让他们共同表决。|v_oath|Freedom|river_assembly|居民取得决定权；有人坚持不迁。',
'挖新旁路，让自己的农田承担第一轮排水。|w_ledger|Sacrifice|gave_farmland|房屋暂时保住；家人失去来年生计。',
'请求教会接纳拒迁的老人，逐户陪同搬走。|h_guard|Mercy|rescued_stayers|老人不再独守；医院空间更拥挤。']),
'v_revolt':('安全领的关卡','安全领只接收与战争无关的人。守卫说你若交出全部证词、炉灰和旧友名单，就可以重新做个普通人。墙内灯火平稳，墙外钟声仍然断断续续。',[
'拒交旧友名单，在城外建立流民营。|v_revolt|Freedom|refused_informant|朋友免遭追查；你失去城墙保护。',
'把灾情交给守卫，只保留无辜者的姓名。|c_ledger|Reason|edited_border_report|边境启动戒备；报告不够完整。',
'把入城名额让给孩子，返回渡口。|v_guard|Sacrifice|returned_for_others|孩子获得安全；你再次走向洪水。',
'接受临时劳役，以自己的工时换营地口粮。|h_guard|Mercy|worked_for_refugees|流民今晚能吃饭；你失去行动时间。']),
'v_guard':('家门里的旧王','失控的记忆从地下传来。你看见艾德里安最后一次回家时，也站在这样一扇修不好的门前。托马说听见真相不等于承担全部责任，但现在已经不能假装没听见。',[
'把记忆写给教会，要求他们派人来解释。|h_ledger|Reason|recorded_memory|证词留下备份；故乡进入官方视线。',
'留在村里修门、做饭，组织彼此照料。|v_guard|Mercy|kept_daily_life|恐惧没有压倒生活；你错过一次权力会谈。',
'循记忆找到旧渠，亲自去见艾德里安。|h_revolt|Courage|sought_previous_hero|普通人也抵达魔王城；故乡暂失你的主持。',
'把家钥匙交给托马，承诺替故乡承担下一次脉冲。|w_oath|Sacrifice|offered_burden|村民获得一夜平静；你开始付出寿命。'])}
D5 = {
'c_oath':('王冠的抵押','莱娅愿给你战时摄政权，条件是继续容器制度。她没有否认制度残酷，只问没有替代方案时谁来承担溃坝。玛伦在桌上放了一封尚未签名的辞职信。',[
'接印，保留继任制度并增设志愿见证。|h_oath|Faith|accepted_crown|命令立刻生效；制度仍需要一个人受苦。',
'接印，把国库抵押给分压工程。|c_ledger|Ambition|accepted_crown|工匠获得资源；失败将让王国破产。',
'拒绝王冠，邀请莱娅以个人身份共同守门。|w_oath|Sacrifice|refused_crown|她第一次没有官职掩护；调度失去中央命令。',
'当众归还印玺，让撤离代表决定下一任。|v_oath|Freedom|refused_crown|代表获得权力；莱娅的忠军保持观望。']),
'c_ledger':('会算错的救命账','维克的分压模型显示，保住中央城区最稳妥的方法是关闭外环三处闸门。奥伦提醒你，那里不是三个点，而是三个仍住着人的街区。',[
'按模型关闭外环，抢救更多中央居民。|c_oath|Reason|sacrificed_innocent|中央屏障稳定；外环有人来不及撤出。',
'先撤空外环再关闭，接受中央失守风险。|v_ledger|Mercy|delayed_seal|被当作数字的人获得时间；核心压力继续上升。',
'把自己的承压器接进外环，替模型补上缺口。|w_oath|Sacrifice|absorbed_overflow|外环多出撤离窗口；你的身体开始失控。',
'公布模型误差，让各街区自行选择支路。|c_revolt|Freedom|published_uncertainty|居民知道真实风险；方案不再统一。']),
'c_revolt':('革命也要钥匙','维克得到粮仓，随后发现开门之后还要分粮。最先支持你的人要求双份；守仓的旧官员熟悉配给，却曾经殴打饥民。',[
'留任旧官员，由受害者监督每日配给。|c_ledger|Reason|supervised_official|配给不必重建；受害者需要再次面对施害者。',
'撤掉所有旧官员，亲自统管粮仓。|c_oath|Ambition|centralized_power|旧势力退出；分粮成了你的独占权。',
'让各营地轮派分粮员，放弃支持者特权。|v_oath|Freedom|abolished_privilege|规则更平等；一部分追随者离去。',
'先补给被抢过的家庭，自己人最后领取。|h_guard|Mercy|repaired_movement_harm|早先伤害得到补偿；盟友认为你偏袒外人。']),
'c_guard':('玛伦没有拔剑','玛伦承认曾奉命烧毁一处魔族哨站，事后才知道地下藏着平民。瓦尔要求交出她作为停火条件。她不求你赦免，只求你不要把她的罪说成误会。',[
'交她受双方共同审判，暂停她的指挥权。|h_ledger|Reason|submitted_maren|受害者得到程序；队伍失去最熟练的骑士。',
'保她继续护送，但记录罪行并承诺战后追责。|c_guard|Mercy|forgave_traitor|撤离保持战力；正义被再次推迟。',
'拒绝用一个人换停火，护送她离开军队。|v_revolt|Freedom|protected_companion|她免遭筹码化；瓦尔撤回停火提议。',
'替她接下最危险的闸门，让她去受审。|w_guard|Sacrifice|took_maren_post|审判与救援可以同时进行；你暴露在洪峰前。']),
'h_oath':('祭坛前的空椅','瑟文辞去教皇之位，以便作为普通志愿者进入容器候选名单。枢机要求你接过权杖，或者让一名主张强制选拔的主教继任。',[
'接权杖，宣布一切承压必须出于知情同意。|h_oath|Faith|accepted_crosier|改革得到宗教权威；仍有人自愿受苦。',
'拆分教皇职权，交给医师与地方教区。|h_ledger|Reason|decentralized_church|单人不再控制选拔；决策要经过协商。',
'烧掉强制候选名单，请信徒自行离开。|h_revolt|Freedom|destroyed_candidate_list|被选中的人重获自由；继任储备骤减。',
'请瑟文留下照料信徒，由你参加承压。|w_oath|Sacrifice|replaced_pope|医院有了熟悉的主持者；你承担他的风险。']),
'h_ledger':('真相的使用说明','研究已证实深渊是旧文明把痛苦从城市抽走后形成的回流海。所谓女神“曙母”曾是保护人的分配意志，后来把稳定凌驾于个人同意。机器中仍有无法归类的回应。',[
'保留分配意志，只删去强制征用权限。|w_ledger|Reason|edited_mother_protocol|系统可继续工作；没人保证它不会再次演变。',
'准备终止分配意志，让各地自行承压。|h_revolt|Freedom|prepared_deicide|强制神谕可能终结；协调能力也将消失。',
'接替它发布命令，让损失由自己决定。|c_oath|Ambition|claimed_oracle|系统暂获明确指令；你走向同一种专断。',
'把回流疼痛传给自己，先叫停无同意抽取。|w_oath|Sacrifice|stopped_extraction|居民不再被秘密抽取；痛苦转入你的身体。']),
'h_revolt':('停火的刀鞘','瓦尔同意让平民撤离，却要把和平写成自己的胜利。妮娅说若签字，失去家人的魔族会再次被军队代表；若不签，今夜就没有通行保证。',[
'签临时停火，只承认通行而不承认胜利。|h_guard|Reason|limited_truce|道路暂时开放；双方宣传仍互相冲突。',
'邀请两族平民代表另签救援公约。|v_oath|Mercy|civilian_pact|平民获得独立声音；军事保护有所减弱。',
'公开瓦尔扣押粮车的证据，逼其退让。|c_revolt|Courage|exposed_var|军方的体面受损；谈判可能变成武斗。',
'用自己作为停火人质，换取无条件通道。|w_guard|Sacrifice|truce_hostage|人群开始通行；你失去下一夜的自由。']),
'h_guard':('医院不能成为国家','医院门口排起要求伊芙裁判战争的长队。她说可以确认谁受了伤，却不能仅凭伤口决定谁拥有土地。病床的数量已经不足以承载所有人的愤怒。',[
'建立证词档案，让医院只负责救治。|h_ledger|Reason|founded_testimony_archive|伤害得到保存；判决被延后。',
'把医院改为跨族避难区，请所有军队缴械。|v_oath|Mercy|neutral_sanctuary|伤者获得缓冲；医院失去军方药品优先权。',
'让伊芙带伤员先走，自己抵押房产买药。|v_guard|Sacrifice|sold_home_for_medicine|药车能出发；故乡不再有属于你的房子。',
'将库存公开，由各病区共同分配。|v_ledger|Freedom|open_medicine_inventory|配药不再依靠关系；争论耗费护理时间。']),
'w_oath':('容器的同意','阿瑟兰教你承压，第一条却是不要把愿意牺牲误当作必须牺牲。艾德里安请求你允许他停止。停止意味着必须立刻找到替代承压者或打开分流。',[
'答应在第七日接替他，留下正式同意书。|h_oath|Faith|promised_succession|旧勇者看见休息的可能；你的未来被承诺占据。',
'请求他再坚持两夜，争取验证分流方案。|w_ledger|Reason|asked_hero_wait|研究获得时间；痛苦仍由他承担。',
'尊重他立即停下的权利，亲自接住第一轮回流。|w_guard|Sacrifice|relieved_hero|他的呼吸第一次平稳；你可能无法撑到天明。',
'拒绝继任制度，邀请所有知情者参加自愿分压。|v_oath|Freedom|called_volunteers|责任不再只落于英雄；共同方案缺乏经验。']),
'w_ledger':('不能保证的第三条路','缇尔的图纸能把深渊回流接回日常生活，代价是大陆不再享有旧文明提供的无痛与恒温。研究中没有全胜，只存在比永久容器更可分担的痛苦。',[
'完成小规模试验，保留失败时的容器接口。|w_ledger|Reason|lattice_validated|技术风险下降；备用接口仍可被滥用。',
'公开图纸，让各城决定是否接入。|v_ledger|Freedom|open_lattice|无人被强迫承担；系统覆盖不完整。',
'用自己的承压器保护试验区居民。|w_guard|Sacrifice|shielded_test|试验区风险下降；你的身体损耗增加。',
'删去安全限幅，换取一夜完成的全功率试验。|w_revolt|Corruption|overclocked_lattice|获得强力数据；试验场留下不可逆污染。']),
'w_revolt':('下一次饥饿','你的力量使军队退开，也使朋友不敢靠近。深渊许诺可以替你承担犹豫，只要你允许它把别人的恐惧当作燃料。那声音并不吼叫，它非常体贴。',[
'接受恐惧供能，要求它不得吞噬同伴。|w_revolt|Corruption|fed_on_fear|力量上升；陌生人的痛苦成了代价。',
'交出承压器，请同伴限制你的力量。|c_guard|Mercy|surrendered_power|朋友可以靠近；你暂时失去威慑。',
'把供能规则公之于众，只接受自愿贡献。|v_oath|Freedom|consensual_power|人们能够拒绝；战力变得不稳定。',
'在无人的地穴自断回路，承担反噬。|w_guard|Sacrifice|broke_corruption|恐惧不再被抽取；你的生命受损。']),
'w_guard':('一枚卵的重量','阿瑟兰愿加入分压，但要求你先保证幼龙绝不承担风险。村里的孩子没有同样的保证。古龙沉默了很久，说它也知道这句话不公平。',[
'拒绝特权，让两族孩子都先撤出试验区。|v_ledger|Mercy|evacuated_children|孩子被同等对待；试验必须推迟。',
'同意保护幼龙，换取古龙立即承压。|w_oath|Reason|dragon_priority|封印得到支撑；人类代表质疑双重标准。',
'请求古龙把保护权交给两族共同照护会。|v_oath|Freedom|shared_dragon_care|跨族共同监护形成；父亲失去单方决定权。',
'自己留下守卵，请古龙去救河岸居民。|v_guard|Sacrifice|exchanged_watch|河岸获得援手；你承担孵化时的灼伤风险。']),
'v_oath':('平民的议事桌','议事会选你作代表，却没有授予你替全体赴死的权利。有人愿参加分压，有人只想离开。托马说，共同生活不能要求每个人都当勇者。',[
'允许拒绝者撤离，余下的人自愿组队。|v_oath|Freedom|protected_refusal|合作出于同意；劳力不足。',
'按技能分工，只让受训者靠近封印。|v_ledger|Reason|trained_volunteers|意外风险下降；未受训者认为自己被排除。',
'把代表席让给两族轮值，自己承担夜班。|v_guard|Sacrifice|gave_up_seat|权力开始流动；你无法主导所有决定。',
'以战时必要为由强制征集承压人员。|c_oath|Ambition|forced_volunteers|工程人手齐备；“志愿”失去了意义。']),
'v_ledger':('最后一船工具','渡口还有一次往返时间。一边是分压工程所需的铜线，一边是尚未撤走的住户。萨德说可以徒手修闸，但有可能再也握不住任何东西。',[
'先送住户，让萨德在安全处等待。|v_guard|Mercy|people_before_tools|居民撤出；工程缺少材料。',
'先送铜线，留下自己陪住户等回程。|w_ledger|Reason|tools_before_people|工程如期开工；你和住户面临洪水。',
'拆掉渡口收费门，制成临时第二艘船。|v_oath|Freedom|broke_tollgate|双方都能启程；地方领主失去财产权。',
'请萨德主导手工修闸，自己承担水下工位。|w_guard|Sacrifice|worked_underwater|工具短缺得到缓解；两人都有受伤风险。']),
'v_revolt':('自由的边界','城外营地没有官员，也没有统一的粮仓。一个家庭拒绝共享食物，却在夜里向你借药。你能坚持自由，也能看见自由无法自动煮出晚饭。',[
'允许拒绝分粮，同时公开所有求助与回应。|v_revolt|Freedom|kept_open_camp|个人选择保留；互信要缓慢重建。',
'建立最低互助契约，参加者共同分配。|v_oath|Reason|mutual_aid_contract|互助有了边界；拒绝者仍可能挨饿。',
'把自己的份额交出去，不要求对方签字。|v_guard|Mercy|unconditional_aid|孩子今晚吃饱；你没有余粮应对明天。',
'返回王都争取物资，接受被通缉的风险。|c_guard|Courage|returned_for_supply|营地可能得到援助；你重新进入权力范围。']),
'v_guard':('门钥匙的去处','家人希望你留在身边，托马希望你帮助全村。两个请求都不卑鄙。黑潮没有等你处理完这些关系，水井里已经出现星光般的黑砂。',[
'留下修井，把研究交给懂它的人。|v_ledger|Reason|trusted_specialists|村里有了安全水；你放弃亲自控制终局。',
'带家人一起参加撤离，不再替他们隐瞒危险。|v_revolt|Freedom|told_family_truth|家人能够决定；他们未必选择与你同行。',
'请托马照看家人，自己去守最后一道闸。|w_guard|Sacrifice|left_key_home|故乡获得时间；你可能不能回来取钥匙。',
'建立轮值照护，让每个家庭都能暂时休息。|h_guard|Mercy|shared_care|责任不再只由一户承担；组织需要耗费体力。'])}
D6 = {
'c_oath':('无人替你签字','战时印玺已经能命令军队，不能命令封印不再破裂。莱娅把自己的名字写入承压名单，表示摄政家族没有豁免。将军们要你在秩序、继任与撤离之间先保住一项。',[
'亲自主持继任仪式，并写明退出权。|h_oath|Faith|consent_rite|仪式得以进行；临阵退出仍可能危及全局。',
'封闭王宫电路，把王冠能源交给工程队。|w_ledger|Reason|released_crown_power|分压工程获得余量；王庭失去独立屏障。',
'留下御印统率卫队，承担终局的全部命令。|c_oath|Ambition|kept_war_power|部队仍然统一；权力集中到你一人。',
'解散强征名册，亲自护送拒绝者离城。|c_guard|Mercy|freed_conscripts|被征者能够离开；封印守卫减少。']),
'c_ledger':('误差栏的签名','维克在最后一版模型上写下失误范围，没有把它藏进脚注。奥伦说如果你愿意删掉这一栏，王庭会追加预算；你们都知道钱也无法取消误差。',[
'保留误差，让各区按知情协议接入。|v_ledger|Reason|shared_load|居民承担明白的风险；覆盖率低于理想值。',
'用军令强制接入，保证系统完整。|c_oath|Ambition|forced_load|模型接近最佳效率；拒绝权消失。',
'把最危险的一路引向自己的承压器。|w_oath|Sacrifice|personal_buffer|试验有了缓冲；你的生还机会下降。',
'暂停全域试验，先让人群通过渡口。|v_guard|Mercy|evacuation_first|即时伤亡风险下降；系统只能争取短期稳定。']),
'c_revolt':('胜利之前的审判','广场要求在日出前处决所有旧官员。维克把一把斧头放在你面前，承认其中有无辜的人，但认为新秩序需要一场不会反悔的胜利。',[
'拒绝集体处决，保护档案和证人。|h_ledger|Reason|stopped_purge|证据得以保存；激进派准备夺权。',
'接过斧头，以恐惧结束争执。|c_revolt|Corruption|killed_innocent|广场暂时安静；无辜者的死亡不能被撤回。',
'交还领导权，带反对屠杀的人去救伤者。|h_guard|Mercy|renounced_purge_power|一部分人离开暴力；你失去政治控制。',
'站在刑台上，要求先审判你自己的命令。|c_guard|Sacrifice|accepted_judgment|问责不再只针对败者；救援失去你的指挥。']),
'c_guard':('骑士的最后一班岗','玛伦所在的审判队与撤离队在山口重逢。双方没有握手，却愿意互换值夜。她说自己不需要清白的结局，只需要今晚别再让别人替她承担命令。',[
'把护送权交给她，自己进封印室谈判。|h_revolt|Courage|trusted_companion_again|她承担公开职责；你把后背交给有罪的人。',
'亲自守山口，让两边伤者先走。|c_guard|Sacrifice|last_rearguard|队伍争到时间；你可能失去入城机会。',
'公开轮值名单，拒绝任何阵营独占道路。|v_oath|Freedom|shared_road|道路成为共同设施；军方优先权受限。',
'严格按速度分流，不为任何熟人插队。|v_ledger|Reason|equal_queue|总撤离效率提高；亲近的人也必须等待。']),
'h_oath':('没有赦罪的祝福','瑟文把权杖放在空椅上，说祝福只表示有人陪伴，不能抹去昨天的伤害。枢机仍要求一个统一口径，外面的信徒则在问他们是否有资格说不。',[
'承认拒绝权，在公开见证下接过权杖。|h_oath|Faith|public_consent|教会仍有共同仪式；服从不再理所当然。',
'把忏悔与赔偿写入继任公约。|h_ledger|Reason|reparation_covenant|旧罪留在记录里；你失去无瑕的公众形象。',
'拆除神谕强制回路，将信仰留给个人。|h_revolt|Freedom|oracle_unbound|神谕不能再征用人；各教区必须自己决定。',
'把候选者全送出门，留下自己值守。|w_oath|Sacrifice|sole_volunteer|没人被推上祭台；你成为唯一的缓冲。']),
'h_ledger':('曙母的第二个答案','分配意志准确说出了你最不愿失去之人的名字。它愿用陌生人的痛苦换这个人的安全。伊芙确认这不是幻觉，却无法证明说话者只是机器或真正的神。',[
'拒绝私人赦免，准备关闭强制分配核心。|h_revolt|Freedom|refused_private_salvation|系统不再偏袒你；私人愿望没有保证。',
'保留计算核心，建立任何人可退出的接口。|w_ledger|Reason|built_exit_switch|社会仍可协调供能；技术需要长期维护。',
'接受交换，先保证自己的同伴存活。|c_oath|Ambition|betrayed_strangers|熟人得到屏障；陌生街区承担压力。',
'由自己承担它索要的份额，拒绝指定替身。|w_oath|Sacrifice|refused_substitute|无人替你支付；你承担过量回流。']),
'h_revolt':('旧勇者请求睡眠','艾德里安已经不能分清屋外是敌军还是春雨。他仍能回答一个问题：若新世界必须让某人永远醒着，他是否愿意再等。他说，愿意不是永远有效的签名。',[
'和他约定交接时刻，不再把同意视为永久。|w_oath|Mercy|hero_consent_renewed|旧勇者保有撤回权；你必须兑现时间。',
'邀请两族医师留下见证他的决定。|h_guard|Reason|shared_witnesses|双方承认同一事实；更多人接近危险核心。',
'要求军队退出，以普通人的身份陪他等天亮。|v_guard|Freedom|dismissed_armies|临终不再是战利品；外部防护削弱。',
'接受残存记忆，承诺替他把被删的名字带出去。|h_ledger|Faith|received_memory|历史不再仅剩官方版本；你的记忆也会受扰动。']),
'h_guard':('最后的病房灯','伊芙让还能走动的人决定自己是否撤离。留在病房的人有信徒，也有不信神的人。药品已经按实际存量公开，没有人被许诺一定能活过明天。',[
'留下维持灯与呼吸机，让医师只管救治。|h_guard|Sacrifice|kept_hospital_light|重伤者继续得到照料；你进入最后撤离批次。',
'把每张病床编入渡口计划，按伤情安排船位。|v_ledger|Reason|planned_bed_evacuation|转运变得可执行；轻伤者必须步行。',
'允许伤者选择自己的陪同者，不按种族分船。|v_guard|Mercy|kept_families_together|家庭不再被制度拆散；部分船只载重不均。',
'把医院钥匙交给共同理事会，拒绝军队接管。|v_oath|Freedom|civil_hospital|医院保有中立；将失去军队优先补给。']),
'w_oath':('剑柄与扶手','封印椅已经按照你的身形调整。无论你有没有黎明，银管都会寻找一个愿意承压的生命。阿瑟兰提醒你，成为容器不是加冕，痛苦也不会自动证明你正确。',[
'签下有限期继任书，要求继任者继续寻找替代。|w_oath|Faith|finite_succession|交接能够开始；世界仍依赖一个身体。',
'拆一段椅管接入分流，给工程最后一次机会。|w_ledger|Reason|opened_backup_channel|多一条替代通路；交接稳定性下降。',
'请求同伴带走黎明的故事，只把痛苦留给自己。|w_guard|Sacrifice|erased_hero_credit|同伴能够离开；你可能不被后世记住。',
'拒绝独自承担，召集仍愿留下的平民。|v_oath|Freedom|rejected_single_vessel|责任可被共同讨论；黎明前的时间所剩无几。']),
'w_ledger':('试验要有人签名','缇尔把能做到的和做不到的分别写在两页纸上：能停止单人囚禁，不能让所有人从此免于痛苦。每个接口旁都留了一个开关，不再只有中央能够决定。',[
'逐区确认同意，启动共同承压的预备网。|v_ledger|Reason|shared_load|分压准备完成；覆盖仍取决于居民自愿。',
'用自己的承压器做总缓冲，保留停机权。|w_oath|Sacrifice|personal_buffer|系统多一次试错；风险集中到你身上。',
'公开全部维修图，让拒绝接入者保留退路。|v_oath|Freedom|open_lattice|技术不再由少数人垄断；统一调度变难。',
'接入未经批准的龙晶，强行提高功率。|w_revolt|Corruption|unlicensed_boost|功率足以压制一轮黑潮；龙晶被永久污染。']),
'w_revolt':('深渊懂得你的名字','体内的回流不再只索要食物，而是索要命令。它愿让你成为最有效率的王，也愿把你塑成所有人都害怕的屏障。没有一种力量会替你决定该伤害谁。',[
'给力量套上自毁锁，请同伴保管钥匙。|w_guard|Reason|power_kill_switch|力量受到外部约束；同伴背负终止你的责任。',
'吸尽周围恐惧，独占封印核心。|w_revolt|Corruption|claimed_abyss|一轮冲击被压住；周围人失去宁静。',
'向受害者交还控制权，接受被永久封禁。|h_guard|Mercy|accepted_restraint|伤害有了制止方式；你的行动受限。',
'自断供能链，把最后的力量送给撤离队。|c_guard|Sacrifice|gave_last_power|撤离屏障增强；你不再能靠力量自保。']),
'w_guard':('天亮前的看守人','龙巢、医院与村庄派来最后一批守门者。每个人都希望你替他们保证明天，但你没有那样的资格。缇尔把备用钥匙交给最年轻的守门人，而不是最强的。',[
'陪守门者轮值，不让任何人独撑到死。|w_guard|Mercy|rotating_watch|每人都有休息；交接可能出现空隙。',
'把龙巢护盾拆开，分别罩住病房与渡口。|v_ledger|Reason|shared_dragon_shield|更多人得到短时保护；龙巢失去完整屏障。',
'让幼龙随难民走，自己守住将熄的炉火。|v_guard|Sacrifice|sent_egg_away|幼龙离开危险区；你留在回流前沿。',
'邀请古龙与平民签共同守望契约。|w_oath|Faith|befriended_dragon|跨族合作得到承诺；双方都必须放弃特权。']),
'v_oath':('没有英雄的会议','你召集的议事会终于不再等你发言。有人支持分流，有人主张撤离，第三个人提出先保存种子。托马把你的椅子移到与大家相同的位置。',[
'支持可撤回的共同承压协议，接受少数人离开。|v_ledger|Freedom|shared_load|程序保留拒绝权；力量并非最大。',
'把指挥交给受训者，自己守住会议后的道路。|c_guard|Sacrifice|yielded_command|专业者得到空间；你的名字可能不在公告里。',
'为种子与儿童保留第一批船位。|v_guard|Mercy|saved_seeds|灾后生活有了起点；部分战斗物资被留下。',
'请求临时独裁到日落，用效率赌信任。|c_oath|Ambition|emergency_dictator|命令迅速执行；交权只剩你的承诺。']),
'v_ledger':('渡船的第七次往返','萨德在最后一块船板上写了维修方法，而不是自己的名字。水面映着王都熄灭的灯。渡口能做的不是击败魔王，是确保有人活着走到下一个早晨。',[
'保留渡船，把全局胜负交给上游工程。|v_ledger|Reason|kept_ferry|本地撤离可靠；你无法亲自掌握大陆结局。',
'拆船作分流浮桥，把个人退路接成公共道路。|v_oath|Freedom|made_public_bridge|更多人能步行撤离；你失去机动撤退工具。',
'把最后一班船留给伤员，自己划回暗处。|v_guard|Sacrifice|last_ferry_return|没人独自等在岸边；你要再次面对洪峰。',
'请两族水手共同守船，让家人先过河。|h_guard|Mercy|mixed_ferry_crew|家人与乘客获得照料；船员必须克服旧怨。']),
'v_revolt':('世界没有追上来','安全领的门再次打开。守卫允许你入城，不再索要旧友名单，只要求放下武器。你终于得到曾经想要的退路，也终于知道退路之外有人仍在等待。',[
'放下武器入城，替幸存者保存真实记忆。|v_revolt|Freedom|chose_exile|你能活着讲述；这次不再返回战场。',
'请守卫接纳孩子，自己回去守最后的路。|c_guard|Courage|returned_final_time|孩子进入城墙；你放弃到手的安全。',
'留在门外接应陌生人，不再加入任何军队。|v_guard|Mercy|independent_relief|流民有了接应者；你没有制度保护。',
'用沿途记录换取工具，送往分压工地。|w_ledger|Reason|traded_route_knowledge|工程得到物资；安全领掌握各方隐秘道路。']),
'v_guard':('你不必成为传说','锅里的汤已经分到最后一碗。家人没有要求你再救任何人，也没有原谅你所有的离开。托马把修好的家钥匙放回你的掌心：无论明天你是什么，今晚仍是家里的人。',[
'留在家与邻人之间，守好最后一盏灯。|v_guard|Mercy|chose_home|熟悉的人不再独处；远处战局不受你控制。',
'把最后的船位留给家人，转身去守闸。|c_guard|Sacrifice|final_rearguard|家人有机会安全抵岸；你放弃同行。',
'将种子、病历和钥匙分别交给三个孩子。|v_ledger|Reason|distributed_future|未来不依赖一名幸存者；你放弃独自保管遗产。',
'拒绝任何封号，只以邻居身份参加共同承压。|v_oath|Freedom|refused_all_titles|共同承担不需要英雄身份；没有人许诺你会被记住。'])}
# Day 7: each menu has different concrete actions, and resolves four distinct roles.
D7 = {
'c_oath':('印玺的日落','王都只剩最后一轮有效命令。摄政的空椅、候选者的签名与关闭一半的城门都在等你的手。拿过权力并不意味着只能留下它，拒绝它也不能让已经签出的命令消失。',[
'戴上王冠，将封印维护纳入公开国法。|king|Ambition|accepted_crown|王国保留统一调度；你必须接受长期问责。',
'用王令组织自愿缓冲，亲自进入承压椅。|vessel|Sacrifice|sacrificed_self|旧容器得以休息；你的身体成为新的封印。',
'撤掉宫墙护盾，先保住中央撤离走廊。|savior|Reason|saved_continent|致命峰值被导离人口核心；王宫不可保全。',
'交还御印，随最后一队难民走出城门。|hero|Freedom|refused_crown|你的命令留下后果；你以普通队员完成护送。']),
'c_ledger':('最后一笔预算','资金、药物与寿命已经写在同一张账上。维克没有填入胜利两个字，奥伦在空栏写了“由谁复核”。系统等着的不是一个不会算错的人，而是肯承认误差的人。',[
'按公开模型分流，保存所有失误记录。|savior|Reason|saved_continent|最大冲击被削弱；受损街区仍需赔偿。',
'把账目交给共同议会，自己留守水闸。|guardian|Sacrifice|held_gate_final|本地安全得到维持；你失去全局指挥。',
'接管国库与维修权，以统一预算重建王国。|king|Ambition|accepted_crown|工程可以延续；财政权集中到你手里。',
'保全原始账簿，带幸存者离开无法再守的城。|witness|Freedom|preserved_records|真相得以传递；城墙最终被放弃。']),
'c_revolt':('刑台与议事桌','人群等你宣布胜利。刑台还没有拆，议事桌已经摆好；同一批木匠造了它们。深渊不会因为旗帜换色而停止，但它的力量可以替任何掌权者让广场安静。',[
'把强制回路接到刑台，建立服从你的秩序。|tyrant|Corruption|enslaved_core|中央秩序恢复；自由被写成需要许可的恩典。',
'拆掉刑台，把木料送去修撤离浮桥。|hero|Mercy|dismantled_scaffold|惩罚被延后；人群获得通行的道路。',
'关闭以神谕征用人的核心，承认协调能力也会失去。|godslayer|Freedom|killed_oracle|强制神谕终止；各地必须共同承担失序。',
'接受公开选举的临时王位，立刻交出审判权。|king|Reason|accepted_crown|权力有了监督；新制度仍可能失败。']),
'c_guard':('路的尽头还有人','撤离队已经看不见王都。玛伦把最后一面盾靠在路边，告诉你山口之后没有观众，也没有能为今晚重新命名的史官。你可以带人过去，也可以留下来。',[
'带最后一队伤者穿过山口，然后放下武器。|hero|Courage|escorted_last|这一队人活着抵达；你无法保证远处的城。',
'留下守住山口，让同行者全部先走。|martyr|Sacrifice|sacrificed_self|队伍脱离追来的黑潮；你没有走出山口。',
'驻守新的边界，让这里永远接纳后来者。|guardian|Mercy|founded_border_watch|流民得到庇护；守望将占据你此后的人生。',
'将指挥交给玛伦，独自寻找失联的村庄。|wanderer|Freedom|walked_unmapped|你放弃稳定归宿；无人照管的地方仍有人抵达。']),
'h_oath':('祷词之后的回答','最后一次钟声并不比人的声音更响。信徒等待仪式，候选者等待确认，瑟文等待有人允许他只做一个老人。仪式能组织人，也能再次遮住人的脸。',[
'接下权杖，把拒绝与退出写成不可删改的教律。|pontiff|Faith|accepted_crosier|教会继续存在；改革必须日复一日执行。',
'自愿接替旧容器，并让见证人定期复核同意。|vessel|Sacrifice|sacrificed_self|封印获得延续；你承担漫长的痛苦。',
'让圣堂供能转向撤离屏障，接受祭坛崩塌。|savior|Mercy|saved_continent|人群越过危险峰值；圣堂失去象征中心。',
'拒绝就职，带着仍愿同行的人走出圣堂。|hero|Freedom|rejected_church|信仰回到个人；教会暂失统一领导。']),
'h_ledger':('不可删去的一页','原件、病历与艾德里安的声音都已存档。现在不是再找到一条秘密就能避免决定的时刻。你可以保存知识，可以改变神谕，也可以承认知识无法替任何人同意。',[
'永久停用强制神谕核心，保存其计算档案。|godslayer|Reason|killed_oracle|强制征用终止；失去中央协调造成长期困难。',
'成立独立记忆馆，陪证人离开封印城。|witness|Freedom|preserved_records|篡改不再容易；你没有亲自终结黑潮。',
'保留仪式，接管教会并开放所有原始档案。|pontiff|Faith|accepted_crosier|信徒仍有共同组织；公开真相引发分裂。',
'把自己的记忆接入缓冲层，为维修队争到时间。|martyr|Sacrifice|sacrificed_self|维修得以完成一轮；你的人格不能完整回来。']),
'h_revolt':('魔王最后的名字','艾德里安请你别在最后仍称他为魔王。他允许别人不同意他的选择，却不愿再被塑成不会疲惫的象征。屋外两族的声音交叠，听起来都像害怕失去家的人。',[
'接替艾德里安，公开承认魔王是一份职责。|vessel|Mercy|became_demon_king|旧勇者得以休息；偏见不会随公告消失。',
'断开强制神谕，与两族共同维护余下的封印。|godslayer|Freedom|killed_oracle|奴役接口被关闭；维护成本由社会承担。',
'尊重他的停止请求，将余压导入预留缓冲。|savior|Reason|released_previous_hero|艾德里安平静死去；缓冲为居民争到存续时间。',
'带走他的证词，护送病房里的平民离城。|witness|Courage|preserved_records|历史有了幸存证人；封印由留下的人接手。']),
'h_guard':('病房门外的黎明','伊芙洗净最后一双手套，问你要不要一起把床推出去。没有人会在史诗里完整写下转运一张床需要多少次停顿，但床上的人会记得经过的每一扇门。',[
'接下医院的终身守护契约，拒绝军事征用。|guardian|Mercy|protected_hospital|伤者有了中立家园；守护并不等于没有敌人。',
'把病床编成船队，亲自带到安全岸。|ferryman|Reason|ferried_beds|病人跨过黑潮支流；物资只能留在原处。',
'留在最后一盏灯下，以生命维持重症屏障。|martyr|Sacrifice|sacrificed_self|重症者等到撤离；你在灯熄后死去。',
'拒绝任何职务，回村照料幸存的邻人。|ordinary|Freedom|chose_ordinary_life|你保有一段普通生活；世界的修复不会因此完成。']),
'w_oath':('椅子不是王座','封印椅发出木头开裂的声音。黎明的传说在你耳中逐渐远去，留下的是一个生命是否愿意继续的简单问题。你没有得到纯洁证明，也没有失去重新选择的资格。',[
'坐进承压椅，接下有期限的魔王职责。|vessel|Faith|became_demon_king|大陆获得下一段时间；继任问题没有消失。',
'站在外环承担第一轮黑潮，掩护所有值守者退后。|martyr|Sacrifice|sacrificed_self|维护者保存下来；你的生命耗尽。',
'以承压训练稳定峰值，再把维护交给共同守望队。|savior|Reason|saved_continent|最危险的一轮过去；长期维护仍需要众人。',
'将封印外门改成共同哨所，与龙族轮值。|guardian|Mercy|shared_watch_final|守门职责不再独占；休息必须以他人的接班换来。']),
'w_ledger':('图纸外的一毫米','最后一枚接头偏离图纸一毫米。缇尔没有隐瞒，工匠们因此多绕了一段铜线。技术拯救人的方式并不总像奇迹，有时只是有人把误差讲了出来。',[
'启动经现场复核的分流，把灾难峰值引向空域。|savior|Reason|saved_continent|大陆避过即时崩塌；污染与维修债留给生者。',
'拆除强制分配中枢，让接口从此只能自愿接入。|godslayer|Freedom|killed_oracle|旧神谕的权力终止；新秩序需要重新协商。',
'把最后的过载引进自己，保住维修人员。|martyr|Sacrifice|sacrificed_self|图纸有人继续执行；你不能看见完成的系统。',
'保存开源图纸，踏上寻找失联节点的道路。|wanderer|Courage|walked_unmapped|知识随你流动；你失去安稳归宿。']),
'w_revolt':('没有人能命令你','深渊的声音愿意服从，条件是你永远不要松手。你第一次拥有足够改变许多人命运的力量，也第一次发现，没有上级并不意味着没有责任。',[
'独占核心，以恐惧维持一座不会反抗的城。|tyrant|Corruption|enslaved_core|城内暂时安定；居民的意志成为燃料。',
'把力量封入自己的身体，停止向他人索取。|vessel|Sacrifice|became_demon_king|黑潮有了新容器；你无法轻易走出封印。',
'用残余力量撕开撤离通道，然后交出控制器。|hero|Mercy|surrendered_power_final|人群得救；你必须面对此前的伤害。',
'拒绝任何限制，向黑潮索取超过身体的力量。|failed|Corruption|lost_self|力量越过容器极限；附近的屏障随你一起破裂。']),
'w_guard':('鳞片与炊烟','幼龙的呼吸不再急促，难民营里升起第一缕炊烟。阿瑟兰说它能守山，却不懂如何让被火伤过的人愿意回来。那不是任何契约能一次完成的工作。',[
'成为两族照护人的一员，守护龙巢与周边村庄。|dragonkeeper|Mercy|kept_dragon_care|共居开始；双方仍需面对旧伤。',
'把龙巢护盾留给病人，自己守住破损外墙。|guardian|Sacrifice|held_gate_final|弱者获得保护；你把余生留在边界。',
'与龙族签公开轮值约，接下第一期容器职责。|vessel|Faith|became_demon_king|封印延续；龙族不能再置身事外。',
'放下看守权，护送幼龙与孩子去新的栖地。|wanderer|Freedom|walked_unmapped|孩子不再继承旧战场；你也告别熟悉的家。']),
'v_oath':('你的椅子也是木头','议事会没有为你准备宝座，只添了一张和大家一样的椅子。共同承压需要签名，最后的道路需要看守，明天的饭需要种子。没有一项能替代另外两项。',[
'签下共同维护协议，亲自参加第一轮承压。|savior|Freedom|collective_final|灾难峰值得到分担；人人仍有长期责任。',
'归还代表徽记，以邻居身份开始重建。|ordinary|Mercy|chose_ordinary_life|你回到日常；制度由其他代表继续维护。',
'接受限期执政职位，把交权日期刻在印玺上。|king|Reason|accepted_crown|调度得到延续；日期能否兑现仍需监督。',
'拒绝王位，带民兵守到最后一名撤离者过桥。|hero|Courage|escorted_last|桥上无人被独留；你付出伤病与时间。']),
'v_ledger':('让明天不再需要一个人','渡口与分压网络同时传来信号。若试验和同意都已落实，这里能接回被转移了七百年的代价；否则它只能帮世界多撑过一次洪峰。没有人可以用愿望代替那些准备。',[
'接通自愿分压网络，把开关留在每个居民手中。|savior|Reason|collective_final|按前置验证决定长期转型或短期稳压；生活将失去旧文明的便利。',
'不冒险扩大系统，完成最后一轮渡运。|ferryman|Mercy|ferried_last|岸边的人得救；大陆封印由别处继续维护。',
'把船位让给同伴，自己留在闸底扳住手轮。|martyr|Sacrifice|sacrificed_self|同伴得以离开；水压最终夺去你的生命。',
'保存水路与维修图，带证人去安全领。|witness|Freedom|preserved_records|下一次灾难不必从零开始；你离开故乡。']),
'v_revolt':('门在你身后关上','安全领允许你登记一个新的职业，不必写下英雄或逃兵。你知道墙外还有未结束的事，也知道活着并不是一件自动获得赦免的事。桌上只有纸、灯和一把普通钥匙。',[
'登记为居民，认真活完这段被争取来的日常。|ordinary|Mercy|chose_ordinary_life|你开始新生活；离开的人仍可能责怪你。',
'承认离开战场，拒绝接受任何追授的荣耀。|exile|Freedom|accepted_exile|身份诚实；你失去方便的英雄叙事。',
'写下所有见闻，包括自己没能回去的那一天。|witness|Reason|preserved_records|记录留下缺口与羞耻；真相不再只由赢家书写。',
'离开安全领，去那些没有出现在地图上的地方。|wanderer|Courage|walked_unmapped|你再次承担未知；没有人许诺你的回归。']),
'v_guard':('第七碗汤','远处的光没有告诉你谁赢了。邻人带来一把种子，孩子把门上的裂缝用布塞好。你等了七天的最后问题，原来不是谁来称你勇者，而是接下来这碗汤端给谁。',[
'留在故乡，照顾活下来的人并承认自己的限度。|ordinary|Mercy|chose_ordinary_life|日常重新开始；失去的人不会因此回来。',
'沿河撑船，把汤和药送给还未过岸的人。|ferryman|Courage|ferried_last|河岸得到接应；你再次离开家门。',
'守在外堤，让村里的人安睡第一夜。|guardian|Sacrifice|held_gate_final|故乡得到缓冲；你的守望还未结束。',
'将龙族与人类留下的孩子一起养大。|dragonkeeper|Freedom|kept_dragon_care|新一代有了共同的家；旧社会未必欢迎它。'])}
# Inventory / irreversible history changes actual final affordances, not just narration.
FINAL_VARIANTS = [
('w_oath','sword',{'all':['took_holy_sword']},'黎明的四种用途','圣剑仍在你的手里。它能切开强制回路，也能充当导流针，能够让军队听令，却不能替任何一种用途证明正当。你已经接受过失去生命的可能；这不等于今天必须交出自己的判断。',[
'将黎明化为导流针，自愿接替旧容器。|vessel|Sacrifice|became_demon_king|圣剑进入封印而非王座；你的生命成为承压边界。',
'用黎明切断神谕征用接口，保留人工维护回路。|godslayer|Freedom|killed_oracle|强制征用被终止；圣剑永久失去完整剑身。',
'将黎明举作停火信号，护送两族伤者离开。|hero|Mercy|sword_as_signal|威望被用来停止追杀；你放弃亲自统治核心。',
'折断黎明释放一次屏障，自己守住崩裂缺口。|martyr|Courage|sacrificed_self|众人得到撤离窗口；你与圣剑一同留在缺口。']),
('w_guard','dragon_debt',{'all':['killed_dragon']},'没有古龙签名的契约','龙族遗誓使带来阿瑟兰的遗骨，没有带来宽恕。护卵与共同照护仍然可以继续，但你不能替死者签下和解。门外有受过你帮助的人，也有认得你手上龙血的人。',[
'接受监督，守住受损龙境并长期偿还赔偿。|guardian|Sacrifice|accepted_dragon_reparation|边界得到保护；你不再拥有自由离开的权利。',
'交出全部屠龙记录，让两族分别保存证词。|witness|Reason|preserved_records|死亡不会被功绩隐去；你接受公开审查。',
'把幼龙交给共同照护会，接受永久离境。|exile|Freedom|accepted_exile|幼龙不必由杀死父亲的人监护；你失去归处。',
'以新的容器职责补上失去的承压支点。|vessel|Faith|became_demon_king|灾难得到一次缓冲；这不是对屠龙的自动赦免。']),
('c_oath','judgment',{'any':['sacrificed_innocent','forced_volunteers','betrayed_strangers']},'加冕之前，先读出名单','原本准备加冕的长桌上摆满了受害者名单。莱娅没有阻止他们入场，卫队也没有替你清空道路。你仍握着印玺，却不再能把所有人的沉默误认为同意。',[
'接受有独立审判监督的王位，公开承担旧令责任。|king|Reason|accepted_crown|王国保有调度；你的罪责不受王位豁免。',
'交出印玺，先完成受害者要求的撤离任务。|hero|Sacrifice|submitted_to_victims|一批人获得救援；你不能据此要求撤回控诉。',
'签下自己的供词，把证据送出王都。|witness|Courage|preserved_records|证据不再受你控制；王位可能由对手取得。',
'让卫队驱逐证人，以封印危机为由永不交权。|tyrant|Ambition|enslaved_core|你的命令不再被打断；受害者失去拒绝的权利。']),
('h_oath','dissent',{'all':['rejected_church']},'曾经离开的人回来了','你曾公开拒绝教会，如今却再次站在圣堂门内。枢机不能把你的返回写作认错，因为你没有撤回当初的质询。信徒在等你说明哪些东西还值得保留，哪些不能再以神的名义继续。',[
'以异议者身份接任，确立任何人都能退出的教律。|pontiff|Faith|accepted_crosier|信仰与质询暂时共处；顽固派拒绝承认你。',
'关闭强制神谕，让圣堂转为自愿救助组织。|godslayer|Freedom|killed_oracle|征用人的权力终止；统一神谕也不再存在。',
'拒绝权杖，保存教会的功绩与罪行原件。|witness|Reason|preserved_records|历史不再只有颂歌或控诉；你失去改革的职位。',
'不向教会效忠，只以个人身份接受容器交接。|vessel|Sacrifice|became_demon_king|封印得到延续；你的同意不属于任何神职者。'])]
