/* Player-visible rendering only; designer values are never displayed. */
(function(){
'use strict';
const D=globalThis.GAME_DATA,E=SeventhDay.createEngine(D),$=s=>document.querySelector(s),app=$('#app');
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const KEY='seventh-day-v1';let state=null,screen='title',busy=false,pending=null,storageOK=true;
let profile={schemaVersion:1,completedRuns:0,collection:{},run:null,runId:null,countedRuns:[]};
function readProfile(){try{const raw=localStorage.getItem(KEY);if(!raw)return;const p=JSON.parse(raw);if(p.schemaVersion!==1||!Number.isInteger(p.completedRuns)||p.completedRuns<0||!p.collection||!Array.isArray(p.countedRuns))throw Error('格式不兼容');if(p.run)E.importSave(p.run);profile=p;}catch(e){storageOK=false;setTimeout(()=>toast('本地存档不可用或损坏；可通过“导出存档”保留本局。'),100);}}
function persist(){try{localStorage.setItem(KEY,JSON.stringify(profile));}catch{storageOK=false;toast('浏览器未允许保存，请导出存档。');}}
function toast(text){document.querySelector('.toast')?.remove();const div=document.createElement('div');div.className='toast';div.role='status';div.textContent=text;document.body.append(div);setTimeout(()=>div.remove(),4500);}
function header(){return `<header class="topbar"><div class="brand"><small>VII</small>第七日的勇者</div><nav class="nav" aria-label="主导航"><button data-action="home">卷首</button><button data-action="collection">命运图鉴</button><button data-action="help">游玩说明</button></nav></header>`;}
function footer(){return `<footer class="footer"><span>SEVEN DAYS, ONE NAME · 末日将至，人尚未定。</span><span>七日 · 每日一择 · 命运留痕</span></footer>`;}
const art=`<svg viewBox="0 0 400 520" role="img" aria-label="古老拱窗中的黎明圣剑"><defs><linearGradient id="glow" x2="0" y2="1"><stop stop-color="#d3b97e" stop-opacity=".16"/><stop offset="1" stop-color="#d3b97e" stop-opacity="0"/></linearGradient><linearGradient id="steel" x2="1" y2="0"><stop stop-color="#d6c491"/><stop offset=".48" stop-color="#f0e4c4"/><stop offset=".51" stop-color="#647d75"/><stop offset="1" stop-color="#9ead96"/></linearGradient></defs><path d="M55 455V205Q55 94 200 22Q345 94 345 205V455Z" fill="url(#glow)" stroke="#b39d65" stroke-opacity=".4"/><path d="M75 446V208Q75 110 200 48Q325 110 325 208V446" fill="none" stroke="#b39d65" stroke-opacity=".25"/><circle cx="200" cy="229" r="107" fill="none" stroke="#c3aa6c" stroke-opacity=".3"/><circle cx="200" cy="229" r="82" fill="none" stroke="#c3aa6c" stroke-opacity=".2"/><path d="M95 229H305M200 70V465M128 152L273 306M272 152L127 306" stroke="#bca471" stroke-opacity=".12"/><path d="M191 194L190 367L200 409L210 367L209 194Z" fill="url(#steel)"/><path d="M151 184Q200 199 249 184L245 199Q200 209 155 199Z" fill="#bca16a"/><path d="M194 139H206V191H194Z" fill="#4d6254" stroke="#bca16a"/><path d="M194 148L206 155M194 160L206 167M194 172L206 179" stroke="#bca16a"/><path d="M191 129L200 118L209 129L200 140Z" fill="#d4ba7e"/><path d="M104 456L151 433L177 449L200 426L230 445L260 439L302 456" fill="none" stroke="#b29d6c" stroke-opacity=".45"/><text x="200" y="493" text-anchor="middle" fill="#8b9b85" font-size="11" letter-spacing="6">LUX NON IUDICAT</text></svg>`;
function title(){return `<main class="hero view-enter"><section><div class="eyebrow">A SEVEN-DAY FANTASY · 交互叙事</div><h1>第七日的<br>勇者</h1><div class="sub">The Hero of the Seventh Dawn</div><p class="pitch">昨天的选择，决定今天你还能选择什么。<br>七天之后，世界会给你一个名字。</p><div class="actions"><button class="primary" data-action="new">${profile.completedRuns?'再走一次七日':'翻开命运之书'} <span aria-hidden="true">→</span></button>${profile.run?'<button class="secondary" data-action="continue">继续旅程</button>':''}</div><p class="muted">每天仅作一次选择 · 一局约 12—20 分钟<br>${profile.completedRuns?'你已走过 '+profile.completedRuns+' 次七日。部分记忆回声已经醒来。':'你不必一开始就知道自己会成为谁。'}</p></section><div class="hero-art">${art}<div class="art-note">在第七声钟响之后，留下你的名字。</div></div></main>`;}
function game(){const v=E.view(state);return `<main class="game view-enter"><div class="dayline"><div class="eyebrow">DAY ${v.day} / VII · ${esc(v.location)}</div><div class="days" aria-label="第 ${v.day} 天，共七天">${Array.from({length:7},(_,i)=>`<span class="dot ${i+1===v.day?'active':i+1<v.day?'past':''}">${i+1}</span>`).join('')}</div></div><h1 class="chapter-title" tabindex="-1">${esc(v.title)}</h1><article class="scene">${v.scene.split('\n\n').map((p,i)=>`<p class="${i===0&&v.day>1?'echo':''}">${esc(p)}</p>`).join('')}</article><div class="choice-label"><div class="eyebrow">在日落之前，你决定——</div><span>选择后当日结束 · 不可回退</span></div><div class="choices">${v.choices.map((c,i)=>`<button class="choice" data-choice="${esc(c.id)}"><span class="num">0${i+1}</span><span><strong>${esc(c.text)}</strong><small>你需要接受：${esc(c.cost)}</small></span></button>`).join('')}</div><p class="save-note">${storageOK?'已在此刻自动保存。':'本地保存不可用，请导出本局。'} 人格与阵营数值保持隐藏。</p><div class="utility"><button data-action="export">导出本局存档</button><button data-action="import">导入本局存档</button></div></main>`;}
function ending(){const r=E.finish(state),p=r.epilogue;const kinds={normal:'一个名字，一段人生',growth:'你的改变，成为了你的名字',contradictory:'功绩与代价，都留在名字里',secret:'一条不常被讲述的道路',true:'一个时代的结束',bad:'故事也会抵达破碎之处'};
const badges=[];if(r.badges.zeroDirectKill)badges.push('本局无直接杀戮');if(r.badges.swordless)badges.push('未取得圣剑');if(r.badges.independent)badges.push('未签阵营效忠');
return `<main class="ending view-enter"><div class="ending-head"><div class="eyebrow">THE SEVENTH DAWN · 七日终章</div><h1 tabindex="-1">《${esc(r.title)}》</h1><p class="muted">${kinds[r.kind]}</p><div class="badge-row">${badges.map(t=>`<span class="badge">${t}</span>`).join('')}</div></div><article class="epilogue"><p>${esc(p.main)}</p><h3>那些与你相遇的人</h3><p>${esc(p.npc)}</p><h3>世界仍在继续</h3><p>${esc(p.world)}</p><h3>而你</h3><p>${esc(p.self)}</p></article><p class="last-line">“${esc(p.last)}”</p><details class="review"><summary>回看塑造这个名字的七次选择</summary>${r.evidence.map(h=>`<div class="history-row"><span>第 ${h.day} 日</span><p>${esc(h.text)}<small>${esc(h.consequence)}</small></p></div>`).join('')}<p class="muted">你的行动倾向：${esc(D.stats[r.dominant])}。${r.arcs.length?'你的经历也形成了人物转变；称号会优先考虑变化和不可撤销的行为。':'这个名字同时考虑了结局身份与前六天的行动。'}这里不展示隐藏分数。</p></details><div class="actions"><button class="primary" data-action="new">如果第一天，我选了另一条路 →</button><button class="secondary" data-action="collection">查看命运图鉴</button></div><div class="utility"><button data-action="export">导出这段旅程</button></div></main>`;}
function collection(){const entries=Object.entries(profile.collection).filter(([id])=>D.endings.some(e=>e.ending_id===id));const active=D.endings.filter(e=>e.reachable!==false);return `<main class="catalog view-enter"><div class="eyebrow">NAMES LEFT BEHIND</div><h1>命运图鉴</h1><p class="muted">已发现 ${entries.length} / ${active.length} 个名字。未发现的名字和条件不会提前揭露。<br>同一世界结果可能对应不同人格与人生评价，称号数量不等于互不相同的世界结局数量。</p><div class="catalog-grid">${entries.map(([id,item])=>`<article class="ending-card"><div class="eyebrow">已发现 · ${esc(D.roles[item.role]?.name||'终章')}</div><h3>《${esc(item.title)}》</h3><p>${esc(item.firstSeen)}</p></article>`).join('')}${Array.from({length:Math.min(12,active.length-entries.length)},()=>'<div class="lock">◇<br>尚未走过的命运</div>').join('')}</div><p class="muted">其余未发现条目保持封存。每条路线每天都只有四个选择。</p><div class="actions"><button class="primary" data-action="new">开始另一段旅程</button>${state?'<button class="secondary" data-action="back">返回本局</button>':''}</div></main>`;}
function render(){app.innerHTML=header()+(screen==='title'?title():screen==='game'?game():screen==='ending'?ending():collection())+footer();document.title='第七日的勇者 · '+({title:'卷首',game:'第'+(state?.day||1)+'日',ending:'七日终章',collection:'命运图鉴'}[screen]);}
function saveRun(){profile.run=E.exportSave(state);persist();}
function record(){const r=E.finish(state);if(!profile.countedRuns.includes(profile.runId)){profile.completedRuns++;profile.countedRuns.push(profile.runId);profile.countedRuns=profile.countedRuns.slice(-1000);profile.collection[r.endingId]??={title:r.title,role:r.role,firstSeen:new Date().toLocaleDateString('zh-CN')};}saveRun();}
function start(){state=E.initial({completedRuns:profile.completedRuns});profile.runId=globalThis.crypto?.randomUUID?.()||Date.now()+'-'+Math.random();saveRun();screen='game';render();window.scrollTo(0,0);}
function confirmNew(){if(profile.run&&profile.run.choiceIds.length>0&&profile.run.choiceIds.length<7){dialog('重新开始？','本局将从第一天开始，已收集的结局会保留。需要保留当前进度时，可以先导出存档。',[['取消',()=>{}],['重新开始',start]]);}else start();}
function dialog(title,text,buttons){document.querySelector('dialog')?.remove();const d=document.createElement('dialog');d.className='dialog';d.innerHTML=`<h2>${esc(title)}</h2><p>${esc(text)}</p><div class="actions">${buttons.map(([t],i)=>`<button class="${i===buttons.length-1?'primary':'secondary'}" data-dialog="${i}">${esc(t)}</button>`).join('')}</div>`;document.body.append(d);d.addEventListener('click',e=>{const b=e.target.closest('[data-dialog]');if(b){d.close();d.remove();buttons[+b.dataset.dialog][1]();}});d.showModal();}
function choose(id){if(busy)return;busy=true;try{state=E.apply(state,id);saveRun();if(state.finished)record();const div=document.createElement('div');div.className='sunset';div.role='dialog';div.setAttribute('aria-modal','true');div.setAttribute('aria-label','今日的后果');const h=state.history.at(-1);div.innerHTML=`<div class="eyebrow">DAY ${h.day} · 日落</div><div class="rule"></div><h2>这一天，已经写下。</h2><p>${esc(h.consequence)}</p><button class="primary" id="next-day">${state.finished?'看见自己的名字':'迎接第 '+state.day+' 日'} →</button>`;document.body.append(div);pending=()=>{div.remove();pending=null;busy=false;screen=state.finished?'ending':'game';render();window.scrollTo(0,0);$('main h1')?.focus();};div.querySelector('button').onclick=pending;div.querySelector('button').focus();}catch(e){busy=false;toast('无法推进：'+e.message);}}
function exportFile(){if(!state){toast('请先开始或继续旅程。');return;}const blob=new Blob([JSON.stringify(E.exportSave(state),null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='seventh-day-save.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
async function importFile(file){if(!file)return;if(file.size>100000){toast('存档文件过大。');return;}try{const s=E.importSave(JSON.parse(await file.text()));const restore=()=>{state=s;profile.runId='import-'+JSON.stringify(s.history.map(h=>h.choiceId));saveRun();screen=state.finished?'ending':'game';if(state.finished)record();render();};if(state&&!state.finished&&state.history.length)dialog('导入并替换当前进度？','你选择的存档通过了七日路径校验。导入将替换本局进度，已有图鉴保留。',[['取消',()=>{}],['导入',restore]]);else restore();}catch(e){toast('未导入：'+e.message);}}
app.addEventListener('click',e=>{const c=e.target.closest('[data-choice]');if(c){choose(c.dataset.choice);return;}const a=e.target.closest('[data-action]')?.dataset.action;if(!a||busy)return;
 if(a==='new')confirmNew();if(a==='home'){screen='title';render();}if(a==='collection'){screen='collection';render();}if(a==='continue'){try{state=E.importSave(profile.run);screen=state.finished?'ending':'game';render();}catch(e){toast('存档无法回放：'+e.message);}}
 if(a==='back'){screen=state.finished?'ending':'game';render();}if(a==='export')exportFile();if(a==='import'){const input=document.createElement('input');input.type='file';input.accept='.json,application/json';input.onchange=()=>importFile(input.files[0]);input.click();}
 if(a==='help')dialog('七天，七次决定','每天固定四个选择，选定后不可在游戏内回退。昨天的行动决定今天进入的处境，重要行为会永久影响结局。浏览器自动保存；也可导出本局。通关解锁记忆回声，不增加第五个选项。人格数值始终隐藏。二周目的准备仍需重新完成。键盘可用 Tab 和 Enter 操作；图鉴只展示已经发现的称号。',[['明白了',()=>{}]]);
});
document.addEventListener('keydown',e=>{if(busy&&e.key==='Tab'){const b=$('#next-day');e.preventDefault();b?.focus();}});
readProfile();render();
})();
